#!/usr/bin/env python3
import sys
import helpers
import nltk
import os
from analyzer import Analyzer
from termcolor import colored


if len(sys.argv) != 2:
    sys.exit("Usage: ./tweets @screen_name")
screen_name = sys.argv[1]

tweets = helpers.get_user_timeline(screen_name, 50)
if tweets == None:
    sys.exit('unable to find user tweets')
else:
    tokenizer = nltk.tokenize.TweetTokenizer()

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            color = 'green'
        elif score < 0.0:
            color = 'red'
        else:
            color = 'yellow'
        print('{}, {}, {}'.format(colored(score, color), colored(tweet, color), colored(screen_name, color)))

